### ISSUE TITLE
Code idea required

### ISSUE THREAD

**Issue by ArcTLK** [ArcTLK/tlkbattlesim#3]
Currently, when a unit is selected from the preselect unit, then a few other units are selected from other select dropdowns, then ranks are changed for those units, an issue occurs due to code falling short.

Possible solutions:
Set unique id to each select element (of the preset unit column), then redefine the ostr, ohp, orstr variables into three different arrays.

**Comment by Azzy420** [comment]
https://github.com/ArcTLK/tlkbattlesim/commit/be2d28759a168eb74fc28b42f761fa65d4c1eec9
